name: OpenSSF Scorecard
on:
  push:
    branches: [main]
  schedule:
    # Run daily at 06:00 UTC
    - cron: '0 6 * * *'
permissions: read-all
jobs:
  scorecard:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: results.json
          results_format: json
          publish_results: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Scorecard results
          path: results.json
          retention-days: 7
